// <auto-generated />
namespace GauchoGrub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class unique_constraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unique_constraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201501260625332_unique_constraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
